### ISSUE TITLE
console service not normal

### ISSUE THREAD

**Issue by spwangxp** [QingCloudAppcenter/rocketmq#4]
测试过程中发现
1，直接新建 4.7.0 版本的集群，console 可以正常工作
2，从 4.3.1 版本升级上来的，若升级前未创建 topic，则升级后 console 可以正常工作。
3，从 4.3.1 升级上来，产生和消费一些消息，则升级后存在较大概率，console 无法正常使用，但删除 console 节点，再新加，则新节点又可以正常工作。

**Comment by hlwanghl** [comment]
console 节点上有挂盘吗？删除节点再增加好像没有什么，如果这都行，那重启一下 console 应该也行吧？

**Comment by spwangxp** [comment]
没挂盘。手动重启进程无效
就是因为这都行，所以感觉有点懵了

**Comment by hlwanghl** [comment]
那是 console 往服务器里写数据了？换个节点 instance id和 IP 变了，把这些信息存进去了？

**Comment by spwangxp** [comment]
nameserver 没有保存数据到磁盘，升级过程中需要先关机，并且 console 启动顺序最后

**Comment by hlwanghl** [comment]
https://github.com/apache/rocketmq-externals/blob/master/rocketmq-console/pom.xml#L24

console 依赖的还是 4.4.0 的版本，这个项目看起来更新不是很及时。

**Comment by hlwanghl** [comment]
不行就 console 别升级，还用老版本的，看有报错吗？对比一下

**Comment by spwangxp** [comment]
目前是这个打算，主要是对比到新版的文件大小都是老版的 4 倍，所以这几天一直卡在这儿。
